name: Build
on:
  push:
  workflow_dispatch:

jobs:
  render-pdf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install typst
        uses: typst-community/setup-typst@v3
      - name: Build PDF
        run:  typst compile main.typ --font-path ./font
      - name : release pdf
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.sha }}
          files: main.pdf