name: Update Website

on:
  push:
    branches: [ "master" ]

jobs:
    call_website:
        runs-on: ubuntu-latest
        steps:
            - name: Repository Dispatch
              uses: peter-evans/repository-dispatch@v3
              with:
                repository: warthog-network/warthog-network.github.io
                event-type: update-submodules